## Append samples you want in your CSV to this file as resources ##
resources:
- controlplane_v1alpha1_kamajicontrolplane.yaml
- controlplane_v1alpha1_kamajicontrolplanetemplate.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
